# @package runner
family: dask
batch_size: 64
task_runner:
  _target_: prefect_dask.DaskTaskRunner
  cluster_class: ??? # dotted path, e.g. dask_kubernetes.operator.KubeCluster
  cluster_kwargs: {}
  adapt_kwargs: {}
