# @package _global_
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  accelerator: auto
  devices: auto
  num_nodes: 1
  precision: 16
  max_epochs: -1
  min_epochs: 1
  gradient_clip_val: 2
  gradient_clip_algorithm: norm
  deterministic: true
  use_distributed_sampler: false
  default_root_dir: ${paths.output_dir}
